// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/applications": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Список приложений разработчика",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID разработчика",
                        "name": "developer_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Размер страницы",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ListApplicationsOutDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponseDTO"
                        }
                    }
                }
            },
            "post": {
                "description": "Загружает APK-файл и создаёт черновик приложения.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Загрузить сборку",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID разработчика",
                        "name": "developer_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Кодовое имя",
                        "name": "code_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID категории (по умолчанию 0)",
                        "name": "category_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Android package name (напр. com.TPU.DIVE_E9)",
                        "name": "android_package_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Локаль по умолчанию (напр. ru)",
                        "name": "default_locale",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название приложения",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Краткий заголовок",
                        "name": "short_title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Версия (напр. 1.0.0)",
                        "name": "version",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Описание",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Цели",
                        "name": "goals",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Задачи",
                        "name": "tasks",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Результаты",
                        "name": "results",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Челленджи",
                        "name": "challenges",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Местоположение",
                        "name": "location",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Обложка видео",
                        "name": "video_cover",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Техника безопасности",
                        "name": "safety",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Видео для web",
                        "name": "web_video",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Видео для in-app",
                        "name": "inapp_video",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Фон для web",
                        "name": "web_background_image",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Фон для in-app (launcher)",
                        "name": "inapp_background_image",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "APK-файл",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.ApplicationOutDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/applications/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Получить приложение",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID приложения",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ApplicationOutDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/applications/{id}/publish": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Опубликовать приложение",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID приложения",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/applications/{id}/verify": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Статус верификации",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID приложения",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.VerificationStatusOutDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponseDTO"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Запустить верификацию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID приложения",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ApplicationOutDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponseDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rest.ApplicationOutDTO": {
            "type": "object",
            "properties": {
                "android_package_name": {
                    "type": "string"
                },
                "apk_filename": {
                    "type": "string"
                },
                "category_id": {
                    "type": "integer"
                },
                "challenges": {
                    "type": "string"
                },
                "code_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "default_locale": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "developer_id": {
                    "type": "string"
                },
                "goals": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inapp_background_image": {
                    "type": "string"
                },
                "inapp_video": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                },
                "results": {
                    "type": "string"
                },
                "safety": {
                    "type": "string"
                },
                "short_title": {
                    "type": "string"
                },
                "tasks": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "verification_process_id": {
                    "type": "string"
                },
                "verification_status": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "video_cover": {
                    "type": "string"
                },
                "web_background_image": {
                    "type": "string"
                },
                "web_video": {
                    "type": "string"
                }
            }
        },
        "rest.ErrorResponseDTO": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "rest.ListApplicationsOutDTO": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.ApplicationOutDTO"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "rest.VerificationStatusOutDTO": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
